baseURL = "/"
languageCode = "en-us"
title = "Clínica Salud Dental"
theme = "universal"
defaultContentLanguage = "es"

[params]
    style = "green"
    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    about_us = "<p>Los mejores tratamientos de estética dental con la mayor confianza</p>"
    address = """<p><strong>Clínica Salud Dental</strong>
        <br>Av. España, 24, bajos
        <br>El Astillero
        <br>39610 Cantabria
        <br>
        <strong>España</strong>
      </p>
      """
    maps = "https://g.page/salmones-unidad-dental"

[params.carousel]
    enable = true